name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main ブランチに push されたときに実行

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 依存関係をインストール
        run: npm ci

      - name: Nuxt.js をビルド
        run: npm run generate

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
